### ISSUE TITLE
Detailed feedback for Ch 01 - part 2

### ISSUE THREAD

**Issue by simoncorstonoliver** [zackchase/mxnet-the-straight-dope#202]
chapter01_crashcourse/linear-algebra.ipynb

* dysfluent: If you're already confident basic linear algebra
* dysfluent: Matrices, which we'll denote with capital letters ($A$, $B$, $C$), are order represented in code as arrays with 2 axes.
* funky layout of math. for a_i,j looks like the a is superscript. 
* Python code treats print as a function which is the default in Python 3 but not Python 2.7. Did I miss something that said the code was Python 3? Code will still work in Python 2.7 but may have parentheses around output to represent a tuple
* groundtruth >> ground truth
* hitherto ->> on this page
* Capitalize "Deep Learning"?

**Comment by zackchase** [comment]
Most changes are great - fixed most of them a while ago but made the final pass just now as I'm cleaning up the issues. One big disagreement:

Capitalize "Deep Learning"? Never. This is becoming more common, but only because class sizes have grown so large that these poor children are left unsupervised to make up their own languages. If there were a Deep Learning Department" then we could capitalize. Same as "mathematics / Mathematics Depaertment". Heuristic: capitalize proper nouns, not buzz words.
