### ISSUE TITLE
fails to run on the list of cpus

### ISSUE THREAD

**Issue by dizcza** [zackchase/mxnet-the-straight-dope#25]
Unable to use all cpu cores.
Notebook P04-C02-cnn-gluon.ipynb.
Changed the second line to `ctx = [mx.cpu(i) for i in range(4)]`
Mxnet's version is 0.10.1 (stable).

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-4359ea201a97> in <module>()
      5     moving_loss = 0.
      6     for i, batch in enumerate(train_data):
----> 7         data = batch.data[0].as_in_context(ctx)
      8         label = batch.label[0].as_in_context(ctx)
      9         with autograd.record():

/Users/dizcza/pkgs/mxnet/python/mxnet/ndarray.py in as_in_context(self, context)
   1022         if self.context == context:
   1023             return self
-> 1024         return self.copyto(context)
   1025 
   1026     def attach_grad(self, grad_req='write'):

/Users/dizcza/pkgs/mxnet/python/mxnet/ndarray.py in copyto(self, other)
    973             return _internal._copyto(self, out=hret)
    974         else:
--> 975             raise TypeError('copyto does not support type ' + str(type(other)))
    976 
    977     def copy(self):

TypeError: copyto does not support type <class 'list'>
```

**Comment by zackchase** [comment]
@mli and @piiswrong can you guys field this one?

**Comment by piiswrong** [comment]
As in context doesn't support list of context as argument.

**Comment by dizcza** [comment]
so how can I run the code with multiple (supposedly all) cpus?

**Comment by zackchase** [comment]
So when you use gluon layers , they can take lists of contexts. Gluon has
one layer of abstraction (a Parameter) that wraps an NDArray. Allowing it
to place the NDArrays on multiple contexts. Possibly the best resources
write now are the tutorial drafts (C14 I think), on multi gpu ML.



On Jul 28, 2017 10:15 AM, "Danylo Ulianych" <notifications@github.com>
wrote:

so how can I run the code with multiple (supposedly all) cpus?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/zackchase/mxnet-the-straight-dope/issues/25#issuecomment-318711506>,
or mute the thread

**Comment by dizcza** [comment]
You can close this issue once the tutorial with multi gpu / cpu is completed.

**Comment by mli** [comment]
the multi-gpus notebooks are committed. i'm going to close this issue
