### ISSUE TITLE
some problems in P01-C03-linear-algebra.ipynb

### ISSUE THREAD

**Issue by koodailar** [zackchase/mxnet-the-straight-dope#76]
the first one is this line:
```nd.dot(A.T, B)```
I think the shape of A and B in the example is good for direct ```nd.dot()``` operation. how do you think?

second one is, near the end of document, the numeric version of norm is calculated as
```nd.sqrt(nd.sum(nd.abs(u)**2))```

why not using ```mx.nd.sqrt(mx.nd.sum(x**2))```, as the ```mx.nd.abs()``` does not make too much sense here

**Comment by zackchase** [comment]
hey thanks for the edits on the draft. the transpose was applied because the shapes of the matrices had been previously assigned so that A and B has same shape. This is condusing because the code didn't parallel the text. I'm committing a change to 

A = nd.ones(shape=(3,4))
B = nd.ones(shape=(4,5))
nd.dot(A, B)

Good catch on the norm. I don't think I wrote it this way originally, thatm ight have slipped in with some copyedits. Thanks for the catch. Or perhaps I'm wrote it cracked out on caffeine. Either way, sorry / thanks!

**Comment by zackchase** [comment]
Fixed in latest commit.
